### ISSUE TITLE
HEMCO standalone crashing for 0.25x0.3125 global grid

### ISSUE THREAD

**Issue by msulprizio** [geoschem/HEMCO#206]
### Name and Institution (Required)

Name: Melissa Sulprizio
Institution: Harvard/GCST

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://hemco.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://hemco.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://hemco.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/HEMCO/issues)

### Description of your issue or question

When running the HEMCO standalone with the 3.7.0 development branch and the 0.25x0.3125 global grid defined in [HEMCO_sa_Grid.025x03125.rc](https://github.com/geoschem/HEMCO/blob/main/run/HEMCO_sa_Grid.025x03125.rc), the simulation crashes with the error:

```
At line 1360 of file /n/home05/msulprizio/S/CH4/hemco_025x03125_geosfp/CodeDir/src/Interfaces/Standalone/hcoi_standalone_mod.F90
Fortran runtime error: End of record

Error termination. Backtrace:
#0  0x2afb80ff7b47 in write_character
        at ../.././libgfortran/io/write.c:1408
#1  0x2afb80ffcb86 in list_formatted_write_scalar
        at ../.././libgfortran/io/write.c:1892
#2  0x407657 in set_grid
        at /n/home05/msulprizio/S/CH4/hemco_025x03125_geosfp/CodeDir/src/Interfaces/Standalone/hcoi_standalone_mod.F90:1341
#3  0x415851 in __hcoi_standalone_mod_MOD_hcoi_sa_init
        at /n/home05/msulprizio/S/CH4/hemco_025x03125_geosfp/CodeDir/src/Interfaces/Standalone/hcoi_standalone_mod.F90:325
#4  0x41662c in __hcoi_standalone_mod_MOD_hcoi_standalone_run
        at /n/home05/msulprizio/S/CH4/hemco_025x03125_geosfp/CodeDir/src/Interfaces/Standalone/hcoi_standalone_mod.F90:194
#5  0x4034dc in hemco_standalone
        at /n/home05/msulprizio/S/CH4/hemco_025x03125_geosfp/CodeDir/src/Interfaces/Standalone/hemco_standalone.F90:136
#6  0x403136 in main
        at /n/home05/msulprizio/S/CH4/hemco_025x03125_geosfp/CodeDir/src/Interfaces/Standalone/hemco_standalone.F90:21
```

After some debugging, I was able to determine that the YEDGE line is being cut off when read because the string length for variable `DUM` in subroutine `Set_Grid` is not long enough.

**Comment by msulprizio** [comment]
The fix for this (PR #207) has now been merged into the 3.7.0 development branch.
